weibo_by_django/apps/miniblog/urls.py
# _*_ coding:utf-8 _*_

from django.contrib import admin
from django.urls import path, include
import xadmin
from django.views.generic import TemplateView

from users.views import user_login, LoginView, RegisterView, ActivateView, FindbackPwd, ResetPwdView, ModifyPwdView
from miniblog.views import MainpageView, SendBlogView, DelBlogView, CollectBlogView, TransferBlogView, CommentBlogView, \
    GoodBlogView, BlogTextPageView, SearchView, EditBLogView,TopicView, AddCommentView

# weibo/xxxx
# app_name = 'miniblog'
urlpatterns = [

    # 发布微博
    path('sendblog/', SendBlogView.as_view(), name='sendblog'),

    # 删除
    path('delblog/<int:blog_id>', DelBlogView.as_view(), name='delblog'),

    # 跳到对应微博正文+评论页面
    path('blogtext/<int:blog_id>', BlogTextPageView.as_view(), name="blogtext"),

    path('collect/<int:blogid>', CollectBlogView.as_view(), name='collect'),
    path('transfer/<int:blogid>', TransferBlogView.as_view(), name='transfer'),
    path('comment/<int:blogid>', CommentBlogView.as_view(), name='comment'),
    path('good/<int:blogid>', GoodBlogView.as_view(), name='good'),
    path('search/', SearchView.as_view(), name='search'),




    path('edit/<int:blogid>', EditBLogView.as_view(), name="editblog"),
    path('topic/<int:topicid>', TopicView.as_view(), name="topic"),

    # 添加一条评论（新增）
    path('add_comment/<int:blog_id>', AddCommentView.as_view(), name='add_comment'),
]

weibo_by_django/apps/operations/urls.py
# _*_ coding:utf-8 _*_

from django.conf.urls import url
from django.urls import path

from .views import AddFollowView, MessageView, UserFollowView, UserFansView, UserInfoView, PwdView, ImageView

app_name = 'operation'

urlpatterns = [
    # 添加关注
    path('add_follow/', AddFollowView.as_view(), name='add_follow'),
    # 用户消息页面
    path('message/', MessageView.as_view(), name='message'),
    # 关注页面
    path('user_follow/<int:userid>', UserFollowView.as_view(), name='user_follow'),
    # 粉丝页面
    path('user_fans/<int:userid>', UserFansView.as_view(), name='user_fans'),
    # 用户信息页面
    path('info/', UserInfoView.as_view(), name='user_info'),
    # 修改密码
    path('pwd/', PwdView.as_view(), name='pwd'),
    path('image/', ImageView.as_view(), name='image')
    # # 添加关注
    # url(r'^add_follow/$', AddFollowView.as_view(), name='add_follow'),
    # # 关注页面
    # url(r'^user_follow/$', UserFollowView.as_view(), name='user_follow'),
    # # 粉丝页面
    # url(r'^user_fans/$', UserFansView.as_view(), name='user_fans'),
]

weibo_by_django/apps/users/urls.py
# _*_ coding:utf-8 _*_

from django.urls import path, include

from users.views import user_login, UserPageView, MyCollectView,MyGoodView

urlpatterns = [

    # 跳到用户主页路由
    path('<int:user_id>/', UserPageView.as_view(), name="userpage"),

    path('mycollect/', MyCollectView.as_view(), name="mycollect"),
    path('mygood/', MyGoodView.as_view(), name="mygood"),
]

weibo_by_django/weibo/urls.py
from django.contrib import admin
from django.urls import path, include
import xadmin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from users.views import user_login, LoginView, RegisterView, ActivateView, FindbackPwd, ResetPwdView, ModifyPwdView, \
    UserPageView, MainPageLoginView, MyCollectView, HotBlogView, LogoutView
from miniblog.views import MainpageView

urlpatterns = [

                  path('xadmin/', xadmin.site.urls),
                  path('login/', LoginView.as_view(), name="login"),
                  # path('', TemplateView.as_view(template_name="MainPage.html")),
                  path('', MainpageView.as_view(), name='mainpage'),
                  path('register/', RegisterView.as_view(), name='register'),
                  path('activate/<str:act_code>', ActivateView.as_view(), name='activate'),
                  path('findbackpwd/', FindbackPwd.as_view(), name='findbackpwd'),
                  path('reset/<str:res_code>', ResetPwdView.as_view(), name="resetpwd"),
                  path('modify/', ModifyPwdView.as_view(), name="modifypwd"),
                  path('captcha/', include('captcha.urls')),

                  # 在主页登录
                  path('mainpagelogin/', MainPageLoginView.as_view(), name='mainpagelogin'),

                  # 用户相关
                  path('user/', include(('users.urls', 'users'), namespace='user')),

                  # 微博主页等
                  path('weibo/', include(('miniblog.urls', 'miniblog'), namespace='weibo')),

                  # 热门微博
                  path('hotblogs/', HotBlogView.as_view(), name="hotblogs"),

                  # 测试路由
                  path('test/', TemplateView.as_view(template_name="LogPage.html")),
                  # （新增）
                  path('index/', MainpageView.as_view(), name='index'),
                  path('logout/', LogoutView.as_view(), name='logout'),
                  # operation相关
                  path('operation/', include('operations.urls', namespace='operation')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 配置media的url处理

weibo_by_django/templates/EditBlog.html
{% extends 'UserPage.html' %}

{% block middlePart %}

<div class="panel panel-default">
                    <div class="panel-body ">

                        <div class="title_area">
                            <p>有什么新鲜事想要告诉大家</p>
                        </div>
                        <div class="form-group ">
                            <form role="form" id="blogcontentform" class="container" enctype="multipart/form-data"
                                  action="{% url "weibo:editblog" blog.id %}" method="post">
                                {% csrf_token %}

                                <!-- <label for="name">文本框</label> -->
                                <textarea class="form-control " id="inputarea" rows="3" name="content" style="width: 45%" placeholder="{{ blog.content }}" onFocus="this" onBlur="this.placeholder='{{ blog.content }}'"></textarea>
                                <p>原图<br><img src="{{ MEDIA_URL }}{{ blog.image }}" style="height:200px;width: 200px;"></p>
                                <img id="cropedBigImg" value='custom' alt="图片区" data-address='' title="上传图片"
                                     style="height: 50px;width: 100px;"/>
                                <label class="ui-upload">图片
                                    <input type="file" style="display: none;" id="chooseImage" name="image">

                                </label>

                                <button type="submit" class="btn btn-info col-sm-offset-3" id="sendblogbtn">发布</button>

                            </form>
                        </div>
                        <!--                           <label for="upload" class="ui-upload">upload</label>
                                                  <input type="file" id="upload" style="display: none;" /> -->


                        {#                        <div class="input_bottom">#}
                        {##}
                        {#                            <button type="button" class="btn right_btn" id="sendblogbtn">发布</button>#}
                        {#                        </div>#}
                    </div>
                    <p id="sendCompanyTips"></p>
                </div>
{% endblock %}


{% block my_js %}
    <script>
    $(function () {

        $('#inputarea').val('{{ blog.content }}').focus().val("{{ blog.content }}")

         $('#chooseImage').on('change', function () {
            var filePath = $(this).val(),         //获取到input的value，里面是文件的路径
                fileFormat = filePath.substring(filePath.lastIndexOf(".")).toLowerCase(),
                src = window.URL.createObjectURL(this.files[0]); //转成可以在本地预览的格式
            // 检查是否是图片
            if (!fileFormat.match(/.png|.jpg|.jpeg/)) {
                error_prompt_alert('上传错误,文件格式必须为：png/jpg/jpeg');
                return;
            }

            $('#cropedBigImg').attr('src', src);

        });

    });


    </script>
{% endblock %}

weibo_by_django/templates/Login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>登录</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
</head>
<body class="text-center container">
<form class="form-signin" action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'images/logo.png' %}" alt="无法显示" style="width:200px;height: 200px;margin-top: 30px">
    <h1 class="h3 mb-3 font-weight-normal">请登录</h1>
    <div class="form-group col-sm-4 offset-sm-4 {% if login_form.errors.username %}errorput{% endif %}">
        <label for="inputUsername" class="sr-only">用户名</label>
        <input type="text" id="inputUsername" class="form-control" placeholder="用户名/邮箱" name="username"
               value="{% if login_form.username.value is not None %}{{ login_form.username.value }}{% endif %}" >
    </div>
    <div class="form-group col-sm-4 offset-sm-4 {% if login_form.errors.password %}errorput{% endif %}">
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="password"
               value="{% if login_form.password.value is not None %}{{ login_form.password.value }}{% endif %}">
    </div>
    <div>
        <p>{% for key,error in login_form.errors.items %}{{ key }}:{{ error }}{% endfor %}</p>
        <p>{{ errmsg }}</p>
    </div>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <a href="{% url "register" %}">注册</a>&emsp;
    <button class="btn btn-primary col-sm-1" type="submit">登录</button>
</form>
    <div>
        <a href="{% url "findbackpwd" %}"><span style="font-size: small">忘记密码</span></a>
        <p class="mt-5 mb-3 text-muted">&copy; 2018-2019</p>
    </div>
</body>
</html>

weibo_by_django/templates/MainSePage.html
{% extends 'MainPage.html' %}

{% block  sech %}
    <li {% if sort == 'time' or sort == '' %}class="active"{% endif %}><a
            href="/">全部</a>
    </li>
    <li {% if sort == 'hot' %}class=""{% endif %}><a href="/?sort=hot">热门</a></li>
    <li {% if sort == 'comment' %}class="active"{% endif %}><a
            href="/?sort=comment">评论</a>
    </li>
{% endblock %}

weibo_by_django/templates/MyCollect.html
{% extends "UserPage.html" %}

{% block title %}我的收藏{% endblock %}

{% block sort %}{% endblock %}

weibo_by_django/templates/SendEmailActivate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>激活邮件已发送，请查看邮箱并激活</p>
<a href="{% url 'login' %}">回到登录</a>
</body>
</html>

weibo_by_django/templates/TopicBlogShow.html
{% extends 'MainPage.html' %}

{% block title %}微博话题{% endblock %}

{% block send_blog %}
<div class="panel panel-default">
    <div class="panel-body">
        <p>关于<a href="{% url 'weibo:topic' the_topic.id %}">#{{ the_topic }}#</a>话题的微博</p>
    </div></div>

{% endblock %}

{% block sort %}
{% endblock %}

weibo_by_django/templates/UserSePage.html
{% extends 'UserPage.html' %}

{% block sech %}{% endblock %}

weibo_by_django/templates/base2.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main2.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/hidden_login.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/hidden_login.js' %}" type="text/javascript"></script>

    {% block custom_js %}{% endblock %}


</head>
<body style="background-image: url({% static 'images/background.png' %})">
<div class="top">
    <div class="top_content">
        <a href="{% url 'index' %}">
            <div class="logo">
                <img src="{% static 'images/logo.png' %}" class="img-rounded img-responsive" style="height: 40px">
            </div>
        </a>
        <div class="search_bar">
            <div class="input-group">
                <input type="text" class="form-control">
                <span class="input-group-btn">
						<button class="btn btn-default" type="button">
							<span class="glyphicon glyphicon-search"></span>
						</button>
					</span>
            </div><!-- /input-group -->
        </div>
        <div class="user_config">
            <ul>
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'register' %}">注册</a></li>
                    <li><a href="{% url 'login' %}">登陆</a></li>
                {% else %}
                    <li><a href="{% url 'logout' %}">注销</a></li>
                    <li><a href="{% url 'operation:user_info' %}">设置</a></li>
                    <li><a href="{% url 'user:userpage' request.user.id %}">{{ request.user.nickname }}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div><!-- top结束 -->

<div class="wrap">
    <div class="main">
        <div class="main_top">
            {% block top %}

            {% endblock %}
        </div>
        <div class="main_left">
            {% block left %}
                <ul class="list-group">
                    <li class="list-group-item">首页</li>
                    <li class="list-group-item">我的收藏</li>
                    <li class="list-group-item">我的赞</li>
                    <li class="list-group-item">热门微博</li>
                </ul>
            {% endblock %}
        </div>

        <div class="main_right">
            {% block right %}

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="login_title">账号登陆</div>
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                            <input type="text" class="form-control" placeholder="输入用户名">
                        </div>
                        <div class="input-group password">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            <input type="password" class="form-control" placeholder="输入密码">
                        </div>
                        <div class="login">
                            <button type="button" class="btn">登陆</button>
                            <a class="forget_pwd">忘记密码</a>
                        </div>

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>这是一个基本的面板</p>
                        <p>这是一个基本的面板</p>
                        <p>这是一个基本的面板</p>
                        <p>这是一个基本的面板</p>
                        <p>这是一个基本的面板</p>
                        <p>这是一个基本的面板</p>
                    </div>
                </div>
            {% endblock %}
        </div>
    </div><!-- main结束 -->
</div><!-- wrap结束 -->

<div class="copyright">
    <div class="copyright_content">
        <ul>
            <li><a href="">关于</a>
                <ul>
                    <li><a href="">品牌故事</a></li>
                    <li><a href="">联系我们</a></li>
                    <li><a href="">加入我们</a></li>
                    <li><a href="">版权声明</a></li>
                </ul>
            </li>
            <li><a href="">课程</a>
                <ul>
                    <li><a href="">品牌故事</a></li>
                    <li><a href="">联系我们</a></li>
                    <li><a href="">加入我们</a></li>
                    <li><a href="">版权声明</a></li>
                </ul>
            </li>
            <li><a href="">留言</a>
                <ul>
                    <li><a href="">品牌故事</a></li>
                    <li><a href="">联系我们</a></li>
                    <li><a href="">加入我们</a></li>
                    <li><a href="">版权声明</a></li>
                </ul>
            </li>
            <li><a href="">关注</a>
                <ul>
                    <li><a href="">品牌故事</a></li>
                    <li><a href="">联系我们</a></li>
                    <li><a href="">加入我们</a></li>
                    <li><a href="">版权声明</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div> <!-- 底部结束 -->


{#    隐藏的登陆框#}
<div class="mini_login" id="mini_login">
    <!-- 表单 -->
    <form action="" method="post">
        <div class="item firstLine" id="firstLine">
            <span class="login_title">我要登录</span>
            <span class="login_close" id="close_minilogin">X</span>
        </div>
        <div class="item">
            <label>用户</label>
            <input type="text" name="uname"/>
        </div>
        <div class="item">
            <label>密码</label>
            <input type="password" name="upwd"/>
        </div>
        <div class="item">
            <a href="javascript:void(0)" class="btn_login" onclick="">登录</a>
        </div>
    </form>
</div>
<!-- 遮罩层 -->
<div class="cover"></div>
</body>
</html>

weibo_by_django/templates/blog_detail.html
{% extends 'base2.html' %}
{% block title %}微博详情页{% endblock %}
{% load static %}
{% block left %}
    <div class="panel panel-default">
        <div class="panel-body">
            微博内容
        </div>
    </div>


{% endblock %}


{% block right %}

    {#微博主题内容#}
    <div class="panel panel-default">

        <div class="panel-body blog_body">
            <div class="overflow_hidden">
                <div class="user_icon">
                    <img src="{{ MEDIA_URL }}{{ blog.user.image }}" class="img-circle img-responsive">
                </div>
                <div class="blog_main">
                    <div class="blog_user">{{ blog.user.nickname }}</div>
                    <div class="blog_time">{{ blog.add_time }}</div>
                    <div class="blog_content">
                        <p>
                            {% autoescape off %}
                                {{ blog.content }}
                            {% endautoescape %}
                        </p>
                    </div>
                    {% if blog.has_pic == 1 %}
                        <div><img src="{{ MEDIA_URL }}{{ blog.image }}"
                                  style="width: 400px;height: 240px;"></div>
                    {% endif %}
                </div>
            </div>

            <div class="blog_bottom">
                <ul>
                    <li><a href="{% url 'weibo:collect' blog.id %}"><span
                            class="glyphicon glyphicon-star-empty">收藏{{ blog.collect_num }} </span></a></li>
                    <li><a href="{% url 'weibo:blogtext' blog.id %}"><span
                            class="glyphicon glyphicon-new-window">阅读{{ blog.click_num }}</span></a></li>
                    <li><a href="{% url 'weibo:blogtext' blog.id %}"><span
                            class="glyphicon glyphicon-comment">评论{{ blog.comment_num }}</span></a></li>
                    <li class="lastItem"><a href="{% url 'weibo:good' blog.id %}"><span
                            class="glyphicon glyphicon-thumbs-up">点赞{{ blog.good_num }}</span></a></li>
                </ul>
            </div>

        </div>

        {#微博评论#}
        <div class="panel-footer comment_div">

            <div class="send_comment" id="comment">
                {#                <form action="" method="post">#}
                <form action="{% url "weibo:add_comment" blog.id %}" method="post">
                    {% csrf_token %}
                    <textarea class="form-control" rows="2" id="blog_text" name="blog_text"></textarea>

                    <div class="submit_button">
                        <button type="button" class="btn-xs submit_comment">发表评论</button>
                    </div>

                </form>
            </div>



            {% for comment in comments %}
                <div class="comment" id="comment">
                    {#                <form action="" method="post">#}
                    <form action="{% url "weibo:add_comment" blog.id %}" method="post">
                        {% csrf_token %}
                        <div class="comment_icon">
                            <img src="{{ MEDIA_URL }}{{ comment.user.image }}" class="img-circle img-responsive">
                        </div>
                        <input type="hidden" name="user_id" value="{{ comment.user.id }}">
                        <div class="comment_main">
                            <a href="{% url 'user:userpage' comment.user.id %}">{{ comment.user.nickname }}</a>
                            {% if comment.reply_user %}
                                回复<a href="{% url 'user:userpage' comment.reply_user.id %}">{{ comment.reply_user }}</a>
                            {% endif %}
                            :{{ comment.comment }}
                            <div class="comment_bottom">
                                <span class="comment_time">{{ comment.add_time }}</span>
                                <div class="comment_bottom_right">
                                    <ul>
                                        <li><a href="">点赞</a></li>
                                        <li><a href="javascript:void(0)" class="comment_a">回复</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="hidden_comment">
                            <textarea class="form-control" rows="1" id="blog_text" name="blog_text"></textarea>

                            <div class="submit_button">
                                <button type="button" class="btn-xs submit_comment">发表评论</button>
                            </div>
                        </div>
                    </form>
                </div>
            {% endfor %}


            {#            <div class="comment" id="comment">#}
            {#                <form action="">#}
            {##}
            {#                <div class="comment_icon">#}
            {#                    <img src="{% static 'images/2018102819422361018.jpg' %}" class="img-circle img-responsive">#}
            {#                </div>#}
            {##}
            {#                <div class="comment_main">#}
            {#                    <a href="">wwqe</a>:BC纪录片《人生七年》，从1964年开始跟拍14个来自不同阶层的孩子，从他们的7岁拍到56岁。半个#}
            {#                    <div class="comment_bottom">#}
            {#                        <span>2017年9月9日</span>#}
            {#                        <div class="comment_bottom_right">#}
            {#                            <ul>#}
            {#                                <li><a href="">点赞</a></li>#}
            {#                                <li><a href="javascript:void(0)" class="comment_a">回复</a></li>#}
            {#                            </ul>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {##}
            {#                    <div class="hidden_comment">#}
            {#                        <textarea class="form-control" rows="1" id="blog_text" name="blog_text"></textarea>#}
            {##}
            {#                        <div class="submit_button">#}
            {#                            <button type="button" class="btn-xs">发表评论</button>#}
            {#                        </div>#}
            {#                     </div>#}
            {#                </form>#}
            {#            </div>#}


        </div>
    </div>
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block custom_js %}
    <script>
        $(document).ready(function () {
            $('.hidden_comment').hide();


            $('.comment_a').click(function () {
                $('.hidden_comment').hide();
                {#$('.hidden_comment').show();#}
                $(this).parents('#comment').find('.hidden_comment').show();
            });


            $('.submit_button').click(function () {
                {% if not request.user.is_authenticated %}
                    shogMinLogin();
                    return false;
                {% endif %}

                {#var text = $(this).parents('#comment').find('textarea').text();#}
                {#alert(text);#}
                var text = $(this).parents('#comment').find('textarea').val();
                {#alert(text);#}
                if (text == "")
                    alert("空文本");
                else {
                    alert(text);
                    $(this).parents('#comment').find('form').submit();
                }


                {#var text = $(this).parents('#comment').find('textarea').html();#}
                {#alert(text);#}
            })

            document.getElementById("close_minilogin").onclick = closeLogin;
            document.getElementById("firstLine").onmousedown = moveLogin;


            function shogMinLogin() {
                var mini_login = document.getElementsByClassName("mini_login")[0];
                var cover = document.getElementsByClassName("cover")[0];
                mini_login.style.display = "block";
                cover.style.display = "block";

                mini_login.style.left = (document.body.scrollWidth - mini_login.scrollWidth) / 2 + "px";
                mini_login.style.top = (document.body.scrollHeight - mini_login.scrollHeight) / 2 + "px";
            }

            /* 关闭登录窗口 */
            function closeLogin() {
                var mini_login = document.getElementsByClassName("mini_login")[0];
                var cover = document.getElementsByClassName("cover")[0];
                mini_login.style.display = "none";
                cover.style.display = "none";
            }

            /* 移动登录窗口 */
            function moveLogin(event) {
                var moveable = true;

                //获取事件源
                event = event ? event : window.event;
                var clientX = event.clientX;
                var clientY = event.clientY;

                var mini_login = document.getElementById("mini_login");
                console.log(mini_login);
                var top = parseInt(mini_login.style.top);
                var left = parseInt(mini_login.style.left);//鼠标拖动
                document.onmousemove = function (event) {
                    if (moveable) {
                        event = event ? event : window.event;
                        var y = top + event.clientY - clientY;
                        var x = left + event.clientX - clientX;
                        if (x > 0 && y > 0) {
                            mini_login.style.top = y + "px";
                            mini_login.style.left = x + "px";
                        }
                    }
                }
                //鼠标弹起
                document.onmouseup = function () {
                    moveable = false;
                }
            }
        })

    </script>
{% endblock %}

weibo_by_django/templates/test.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>
    <link rel='stylesheet' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'>
    <link rel="stylesheet" href="{% static 'css/test.css'  %}" type="text/css">
    <style href=""></style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <form class="form-horizontal">
                <span class="heading">用户登录</span>
                <div class="form-group">
                    <input type="email" class="form-control" id="inputEmail3" placeholder="用户名或电子邮件">
                    <i class="fa fa-user"></i>
                </div>
                <div class="form-group help">
                    <input type="password" class="form-control" id="inputPassword3" placeholder="密　码">
                    <i class="fa fa-lock"></i>
                    <a href="#" class="fa fa-question-circle"></a>
                </div>
                <div class="form-group">
                    <div class="main-checkbox">
                        <input type="checkbox" value="None" id="checkbox1" name="check"/>
                        <label for="checkbox1"></label>
                    </div>
                    <span class="text">Remember me</span>
                    <button type="submit" class="btn btn-default">登录</button>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>